#pragma once
#include <ntddk.h>

#define IO_READ_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x100, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define IO_WRITE_MEMORY CTL_CODE(FILE_DEVICE_UNKNOWN, 0x200, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

NTSTATUS IoControl(PDRIVER_OBJECT deviceObject, PIRP irp);

NTSTATUS CloseCall(PDRIVER_OBJECT deviceObject, PIRP irp);

NTSTATUS CreateCall(PDRIVER_OBJECT deviceObject, PIRP irp);
